forge 'forge.puppetlabs.com'

# Forge Modules
mod 'biemond/oradb'
mod 'elasticsearch/elasticsearch'
mod 'elasticsearch/logstash'
mod 'example42/yum'
mod 'example42/puppi'
mod 'ghoneycutt/hosts'
mod 'hubspot/nexus'
mod 'jfryman/nginx'
mod 'jlambert121/kibana'
mod 'maestrodev/wget'
mod 'pcfens/filebeat'
mod 'puppet/archive'
mod 'puppetlabs/accounts'
mod 'puppetlabs/concat'
mod 'puppetlabs/java'
mod 'puppetlabs/limits'
mod 'puppetlabs/ntp'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'thias/sysctl'
mod 'vshn/gitlab'
mod 'wdijkerman/zabbix'
