forge 'forge.puppetlabs.com'

# Forge Modules
mod 'example42/yum'
mod 'example42/puppi'
mod 'ghoneycutt/hosts'
mod 'hubspot/nexus'
mod 'jfryman/nginx'
mod 'maestrodev/wget'
mod 'puppet/archive'
mod 'puppetlabs/concat'
mod 'puppetlabs/java'
mod 'puppetlabs/ntp'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'vshn/gitlab'
mod 'wdijkerman/zabbix'
